version: '3'

services:

  bookreviewer-postgres:
    image: "postgres:15.2-alpine"
    container_name: bookreviewer-postgres

    volumes:
      - bookreviewer-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_data.sql:/docker-entrypoint-initdb.d/fill_data.sql
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd

  app:
    build: ./app
    container_name: app

    environment:
      - DB_SERVER=bookreviewer-postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    ports:
      - 8080:8080
    links:
      - bookreviewer-postgres

volumes:
  bookreviewer-data: